language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# Workaround (cf. https://github.com/travis-ci/travis-ci/issues/9815):
# Enable 3.7 without globally enabling sudo and dist
# Use xenial for other build jobs
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
install:
  - pip install tox-travis
script:
  - tox
